"""create legend_entries table

Revision ID: 15bc524c492f
Revises: 709345772063
Create Date: 2026-08-25 22:24:59.024088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15bc524c492f'
down_revision: Union[str, Sequence[str], None] = '709345772063'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('legend_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('plan_page_id', sa.UUID(), nullable=False),
    sa.Column('pattern_x', sa.Float(), nullable=True),
    sa.Column('pattern_y', sa.Float(), nullable=True),
    sa.Column('pattern_width', sa.Float(), nullable=True),
    sa.Column('pattern_height', sa.Float(), nullable=True),
    sa.Column('pattern_image_reference', sa.String(length=1000), nullable=True),
    sa.Column('description_x', sa.Float(), nullable=True),
    sa.Column('description_y', sa.Float(), nullable=True),
    sa.Column('description_width', sa.Float(), nullable=True),
    sa.Column('description_height', sa.Float(), nullable=True),
    sa.Column('description_image_reference', sa.String(length=1000), nullable=True),
    sa.Column('raw_ocr_text', sa.Text(), nullable=True),
    sa.Column('corrected_text', sa.Text(), nullable=True),
    sa.Column('material_name', sa.String(length=255), nullable=True),
    sa.Column('material_code', sa.String(length=100), nullable=True),
    sa.Column('thickness_mm', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'ocr_complete', 'confirmed', name='legend_entry_status'), server_default='draft', nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_page_id'], ['plan_pages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legend_entries_plan_id'), 'legend_entries', ['plan_id'], unique=False)
    op.create_index(op.f('ix_legend_entries_plan_page_id'), 'legend_entries', ['plan_page_id'], unique=False)
    op.create_index(op.f('ix_legend_entries_project_id'), 'legend_entries', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_legend_entries_project_id'), table_name='legend_entries')
    op.drop_index(op.f('ix_legend_entries_plan_page_id'), table_name='legend_entries')
    op.drop_index(op.f('ix_legend_entries_plan_id'), table_name='legend_entries')
    op.drop_table('legend_entries')
    # ### end Alembic commands ###
    # Autogenerate does not emit this (same gap fixed in the R1/R2
    # migrations): Postgres ENUM types are separate objects from the
    # columns that use them, so dropping the table leaves the type behind.
    # Without this, a subsequent upgrade would fail with "type ... already
    # exists".
    sa.Enum(name='legend_entry_status').drop(op.get_bind(), checkfirst=True)
