"""create plans and plan_pages tables

Revision ID: 709345772063
Revises: 72c82e8ce581
Create Date: 2026-08-14 00:16:40.569373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '709345772063'
down_revision: Union[str, Sequence[str], None] = '72c82e8ce581'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('stored_file_reference', sa.String(length=1000), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('processing_status', sa.Enum('uploaded', 'inspecting', 'ready', 'failed', name='plan_processing_status'), server_default='uploaded', nullable=False),
    sa.Column('pdf_type', sa.Enum('vector', 'raster', 'mixed', 'unknown', name='plan_pdf_type'), server_default='unknown', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plans_project_id'), 'plans', ['project_id'], unique=False)
    op.create_table('plan_pages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('rotation', sa.Integer(), nullable=False),
    sa.Column('vector_content_available', sa.Boolean(), nullable=False),
    sa.Column('preview_reference', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'page_number', name='uq_plan_pages_plan_id_page_number')
    )
    op.create_index(op.f('ix_plan_pages_plan_id'), 'plan_pages', ['plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plan_pages_plan_id'), table_name='plan_pages')
    op.drop_table('plan_pages')
    op.drop_index(op.f('ix_plans_project_id'), table_name='plans')
    op.drop_table('plans')
    # ### end Alembic commands ###
    # Autogenerate does not emit these (same gap fixed in the R1 migration):
    # Postgres ENUM types are separate objects from the columns that use
    # them, so dropping the tables leaves both types behind. Without this, a
    # subsequent upgrade would fail with "type ... already exists".
    sa.Enum(name='plan_pdf_type').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='plan_processing_status').drop(op.get_bind(), checkfirst=True)
