"""create detection engine tables

Revision ID: 90498cc645d2
Revises: be2de4578b1a
Create Date: 2026-08-28 16:47:46.248537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90498cc645d2'
down_revision: Union[str, Sequence[str], None] = 'be2de4578b1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detection_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('plan_page_id', sa.UUID(), nullable=False),
    sa.Column('reference_legend_entry_id', sa.UUID(), nullable=True),
    sa.Column('reference_pattern_library_entry_id', sa.UUID(), nullable=True),
    sa.Column('feature_version', sa.String(length=20), nullable=False),
    sa.Column('detector_version', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', name='detection_run_status'), server_default='pending', nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('tile_count', sa.Integer(), nullable=False),
    sa.Column('tiles_evaluated', sa.Integer(), nullable=False),
    sa.Column('tiles_skipped', sa.Integer(), nullable=False),
    sa.Column('candidate_region_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('(reference_legend_entry_id IS NOT NULL) != (reference_pattern_library_entry_id IS NOT NULL)', name='ck_detection_runs_exactly_one_reference'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_page_id'], ['plan_pages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reference_legend_entry_id'], ['legend_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reference_pattern_library_entry_id'], ['pattern_library_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detection_runs_plan_id'), 'detection_runs', ['plan_id'], unique=False)
    op.create_index(op.f('ix_detection_runs_plan_page_id'), 'detection_runs', ['plan_page_id'], unique=False)
    op.create_index(op.f('ix_detection_runs_project_id'), 'detection_runs', ['project_id'], unique=False)
    op.create_index(op.f('ix_detection_runs_reference_legend_entry_id'), 'detection_runs', ['reference_legend_entry_id'], unique=False)
    op.create_index(op.f('ix_detection_runs_reference_pattern_library_entry_id'), 'detection_runs', ['reference_pattern_library_entry_id'], unique=False)
    op.create_table('detected_regions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('detection_run_id', sa.UUID(), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('similarity', sa.Float(), nullable=False),
    sa.Column('evidence_coverage', sa.Float(), nullable=False),
    sa.Column('tile_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('candidate', 'accepted', 'rejected', name='detected_region_status'), server_default='candidate', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['detection_run_id'], ['detection_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detected_regions_detection_run_id'), 'detected_regions', ['detection_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detected_regions_detection_run_id'), table_name='detected_regions')
    op.drop_table('detected_regions')
    # autogenerate never emits these -- same gap fixed in every prior
    # migration that introduced a native enum column. Without them, the
    # enum types survive downgrade and the next upgrade fails trying to
    # recreate them.
    sa.Enum(name='detected_region_status').drop(op.get_bind(), checkfirst=True)
    op.drop_index(op.f('ix_detection_runs_reference_pattern_library_entry_id'), table_name='detection_runs')
    op.drop_index(op.f('ix_detection_runs_reference_legend_entry_id'), table_name='detection_runs')
    op.drop_index(op.f('ix_detection_runs_project_id'), table_name='detection_runs')
    op.drop_index(op.f('ix_detection_runs_plan_page_id'), table_name='detection_runs')
    op.drop_index(op.f('ix_detection_runs_plan_id'), table_name='detection_runs')
    op.drop_table('detection_runs')
    sa.Enum(name='detection_run_status').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
