"""create hatch_feature_sets table

Revision ID: a81445a2120c
Revises: 15bc524c492f
Create Date: 2026-08-27 00:27:20.757982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a81445a2120c'
down_revision: Union[str, Sequence[str], None] = '15bc524c492f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hatch_feature_sets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('legend_entry_id', sa.UUID(), nullable=False),
    sa.Column('feature_version', sa.String(length=20), nullable=False),
    sa.Column('source_width', sa.Integer(), nullable=False),
    sa.Column('source_height', sa.Integer(), nullable=False),
    sa.Column('dominant_angles', sa.JSON(), nullable=False),
    sa.Column('is_cross_hatch', sa.Boolean(), nullable=True),
    sa.Column('normalized_line_spacing', sa.Float(), nullable=True),
    sa.Column('line_density', sa.Float(), nullable=False),
    sa.Column('normalized_line_width', sa.Float(), nullable=True),
    sa.Column('periodicity', sa.Float(), nullable=True),
    sa.Column('color_mean_l', sa.Float(), nullable=False),
    sa.Column('color_mean_a', sa.Float(), nullable=False),
    sa.Column('color_mean_b', sa.Float(), nullable=False),
    sa.Column('color_std_l', sa.Float(), nullable=False),
    sa.Column('color_std_a', sa.Float(), nullable=False),
    sa.Column('color_std_b', sa.Float(), nullable=False),
    sa.Column('detected_line_count', sa.Integer(), nullable=False),
    sa.Column('angle_evidence_strength', sa.Float(), nullable=False),
    sa.Column('spacing_available', sa.Boolean(), nullable=False),
    sa.Column('periodicity_available', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['legend_entry_id'], ['legend_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hatch_feature_sets_legend_entry_id'), 'hatch_feature_sets', ['legend_entry_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hatch_feature_sets_legend_entry_id'), table_name='hatch_feature_sets')
    op.drop_table('hatch_feature_sets')
    # ### end Alembic commands ###
