"""create pattern library tables

Revision ID: be2de4578b1a
Revises: a81445a2120c
Create Date: 2026-08-28 02:29:48.778149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be2de4578b1a'
down_revision: Union[str, Sequence[str], None] = 'a81445a2120c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pattern_library_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('source_legend_entry_id', sa.UUID(), nullable=False),
    sa.Column('hatch_feature_set_id', sa.UUID(), nullable=False),
    sa.Column('canonical_material_name', sa.String(length=255), nullable=False),
    sa.Column('material_code', sa.String(length=100), nullable=True),
    sa.Column('thickness_mm', sa.Float(), nullable=True),
    sa.Column('original_label', sa.Text(), nullable=True),
    sa.Column('confirmation_count', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hatch_feature_set_id'], ['hatch_feature_sets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_legend_entry_id'], ['legend_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pattern_library_entries_hatch_feature_set_id'), 'pattern_library_entries', ['hatch_feature_set_id'], unique=False)
    op.create_index(op.f('ix_pattern_library_entries_project_id'), 'pattern_library_entries', ['project_id'], unique=False)
    op.create_index(op.f('ix_pattern_library_entries_source_legend_entry_id'), 'pattern_library_entries', ['source_legend_entry_id'], unique=True)
    op.create_table('pattern_match_decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('candidate_legend_entry_id', sa.UUID(), nullable=False),
    sa.Column('suggested_library_entry_id', sa.UUID(), nullable=True),
    sa.Column('similarity_at_decision', sa.Float(), nullable=True),
    sa.Column('decision', sa.Enum('accepted', 'rejected', 'manual', name='pattern_match_decision_kind'), nullable=False),
    sa.Column('confirmed_material_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_legend_entry_id'], ['legend_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['suggested_library_entry_id'], ['pattern_library_entries.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pattern_match_decisions_candidate_legend_entry_id'), 'pattern_match_decisions', ['candidate_legend_entry_id'], unique=False)
    op.create_index(op.f('ix_pattern_match_decisions_project_id'), 'pattern_match_decisions', ['project_id'], unique=False)
    op.create_index(op.f('ix_pattern_match_decisions_suggested_library_entry_id'), 'pattern_match_decisions', ['suggested_library_entry_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pattern_match_decisions_suggested_library_entry_id'), table_name='pattern_match_decisions')
    op.drop_index(op.f('ix_pattern_match_decisions_project_id'), table_name='pattern_match_decisions')
    op.drop_index(op.f('ix_pattern_match_decisions_candidate_legend_entry_id'), table_name='pattern_match_decisions')
    op.drop_table('pattern_match_decisions')
    # autogenerate never emits this -- same gap fixed in every prior
    # migration that introduced a native enum column (see legend_entry's
    # own migration). Without it, the enum type survives downgrade and
    # the next upgrade fails trying to recreate it.
    sa.Enum(name='pattern_match_decision_kind').drop(op.get_bind(), checkfirst=True)
    op.drop_index(op.f('ix_pattern_library_entries_source_legend_entry_id'), table_name='pattern_library_entries')
    op.drop_index(op.f('ix_pattern_library_entries_project_id'), table_name='pattern_library_entries')
    op.drop_index(op.f('ix_pattern_library_entries_hatch_feature_set_id'), table_name='pattern_library_entries')
    op.drop_table('pattern_library_entries')
    # ### end Alembic commands ###
