"""R7 review and quantity integration

Revision ID: c61d4d05e4c9
Revises: 90498cc645d2
Create Date: 2026-08-28 18:35:54.869428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c61d4d05e4c9'
down_revision: Union[str, Sequence[str], None] = '90498cc645d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_scales',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('plan_page_id', sa.UUID(), nullable=False),
    sa.Column('method', sa.Enum('declared_scale', 'calibrated_distance', name='plan_scale_method'), nullable=False),
    sa.Column('declared_ratio', sa.Float(), nullable=True),
    sa.Column('calibrated_distance_plan_points', sa.Float(), nullable=True),
    sa.Column('calibrated_distance_real_m', sa.Float(), nullable=True),
    sa.Column('real_meters_per_plan_point', sa.Float(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_page_id'], ['plan_pages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_scales_plan_id'), 'plan_scales', ['plan_id'], unique=False)
    op.create_index(op.f('ix_plan_scales_plan_page_id'), 'plan_scales', ['plan_page_id'], unique=True)
    op.create_index(op.f('ix_plan_scales_project_id'), 'plan_scales', ['project_id'], unique=False)
    op.create_table('manual_region_corrections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('plan_page_id', sa.UUID(), nullable=False),
    sa.Column('detection_run_id', sa.UUID(), nullable=False),
    sa.Column('correction_type', sa.Enum('add', 'subtract', name='manual_correction_type'), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['detection_run_id'], ['detection_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_page_id'], ['plan_pages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manual_region_corrections_detection_run_id'), 'manual_region_corrections', ['detection_run_id'], unique=False)
    op.create_index(op.f('ix_manual_region_corrections_plan_id'), 'manual_region_corrections', ['plan_id'], unique=False)
    op.create_index(op.f('ix_manual_region_corrections_plan_page_id'), 'manual_region_corrections', ['plan_page_id'], unique=False)
    op.create_index(op.f('ix_manual_region_corrections_project_id'), 'manual_region_corrections', ['project_id'], unique=False)
    op.create_table('quantity_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('plan_page_id', sa.UUID(), nullable=False),
    sa.Column('detection_run_id', sa.UUID(), nullable=False),
    sa.Column('final_area_m2', sa.Float(), nullable=False),
    sa.Column('confirmed_dimension_m', sa.Float(), nullable=False),
    sa.Column('volume_m3', sa.Float(), nullable=False),
    sa.Column('calculation_version', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('draft', 'confirmed', name='quantity_result_status'), server_default='draft', nullable=False),
    sa.Column('accepted_region_count', sa.Integer(), nullable=False),
    sa.Column('manual_add_count', sa.Integer(), nullable=False),
    sa.Column('manual_subtract_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['detection_run_id'], ['detection_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_page_id'], ['plan_pages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quantity_results_detection_run_id'), 'quantity_results', ['detection_run_id'], unique=True)
    op.create_index(op.f('ix_quantity_results_plan_id'), 'quantity_results', ['plan_id'], unique=False)
    op.create_index(op.f('ix_quantity_results_plan_page_id'), 'quantity_results', ['plan_page_id'], unique=False)
    op.create_index(op.f('ix_quantity_results_project_id'), 'quantity_results', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quantity_results_project_id'), table_name='quantity_results')
    op.drop_index(op.f('ix_quantity_results_plan_page_id'), table_name='quantity_results')
    op.drop_index(op.f('ix_quantity_results_plan_id'), table_name='quantity_results')
    op.drop_index(op.f('ix_quantity_results_detection_run_id'), table_name='quantity_results')
    op.drop_table('quantity_results')
    # autogenerate never emits this -- same gap fixed in every prior
    # migration that introduced a native enum column (R1-R6). Without it,
    # the enum type survives downgrade and the next upgrade fails trying
    # to recreate it.
    sa.Enum(name='quantity_result_status').drop(op.get_bind(), checkfirst=True)
    op.drop_index(op.f('ix_manual_region_corrections_project_id'), table_name='manual_region_corrections')
    op.drop_index(op.f('ix_manual_region_corrections_plan_page_id'), table_name='manual_region_corrections')
    op.drop_index(op.f('ix_manual_region_corrections_plan_id'), table_name='manual_region_corrections')
    op.drop_index(op.f('ix_manual_region_corrections_detection_run_id'), table_name='manual_region_corrections')
    op.drop_table('manual_region_corrections')
    sa.Enum(name='manual_correction_type').drop(op.get_bind(), checkfirst=True)
    op.drop_index(op.f('ix_plan_scales_project_id'), table_name='plan_scales')
    op.drop_index(op.f('ix_plan_scales_plan_page_id'), table_name='plan_scales')
    op.drop_index(op.f('ix_plan_scales_plan_id'), table_name='plan_scales')
    op.drop_table('plan_scales')
    sa.Enum(name='plan_scale_method').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
